edition = 4

[agent]
name = "klavis-google-calendar"
version = "1.0.0"
license = { type = "spdx", expression = "MIT" }

description = "An agent with full Google calendar access"

summary = "A KlavisAI Google Calendar agent."
readme = """
This agent requires a Klavis AI account. 

1. Create an account on [KlavisAI](https://klavis.ai/) if you don't have one.
2. Find the Google Calendar MCP server
3. Authorize Klavis to access your Google Calendar account
4. Hit "Show Individual Server URL" and use the value for this agent's `KLAVIS_MCP_URL` option.

Warning: Consider enabling read only mode in Klavis.  If this agent is given read and write access it potentially violates the [Rule of Two](https://ai.meta.com/blog/practical-ai-agent-security/)
"""

[[llm.proxies]]
name = "OPENAI"
format.type = "OpenAI"
models = ["gpt-5.1-mini"]

[runtimes.prototype]
iterations = { type = "option", name = "ITERATION_COUNT" }
delay = { type = "option", name = "ITERATION_DELAY" }
proxy = "OPENAI"

[[runtimes.prototype.tools]]
type = "mcp_streamable_http"
url = { type = "option", name = "KLAVIS_MCP_URL" }

[runtimes.prototype.prompts.system]
base = { type = "option", name = "BASE_SYSTEM_PROMPT" }
extra = { type = "option", name = "EXTRA_SYSTEM_PROMPT" }

[runtimes.prototype.prompts.loop]
initial.base = { type = "option", name = "LOOP_INITIAL_BASE_PROMPT" }
initial.extra = { type = "option", name = "LOOP_INITIAL_EXTRA_PROMPT" }
followup = { type = "option", name = "LOOP_FOLLOWUP_PROMPT" }

##
## Klavis
##
[options.KLAVIS_MCP_URL]
type = "string"
required = true
secret = true
display.group = "KlavisAI"
display.description = "Example: https://mcp-server.klavis.ai/mcp/?instance_id=..."

##
## Prompts
##
[options.BASE_SYSTEM_PROMPT]
type = "string"
display.multiline = true
display.group = "Prompts"
default = { type = "constant", name = "PROTOTYPE_DEFAULT_SYSTEM_PROMPT" }

[options.EXTRA_SYSTEM_PROMPT]
type = "string"
display.multiline = true
display.group = "Prompts"
default = "You are an agent with special tools to interact with Google Calendar. Use the google_calendar_* tooling to best assist other agents as requested."

[options.LOOP_INITIAL_BASE_PROMPT]
type = "string"
display.multiline = true
display.group = "Prompts"
default = { type = "constant", name = "PROTOTYPE_DEFAULT_LOOP_INITIAL_BASE_PROMPT" }

[options.LOOP_INITIAL_EXTRA_PROMPT]
type = "string"
display.multiline = true
display.group = "Prompts"
required = false

[options.LOOP_FOLLOWUP_PROMPT]
type = "string"
display.multiline = true
display.group = "Prompts"
default = { type = "constant", name = "PROTOTYPE_DEFAULT_LOOP_FOLLOWUP_PROMPT" }

##
## Iteration control
## 
[options.ITERATION_COUNT]
type = "i32"
display.group = "Iteration"
display.description = "Number of times the agent will loop, taking actions and observing results, before it stops."
default = 20

[options.ITERATION_DELAY]
type = "i32"
display.group = "Iteration"
display.description = "Delay between each iteration of the agent's loop, in milliseconds."
default = 0