edition = 3

[agent]
name = "firecrawl"
version = "0.2.5"
summary = "An agent that can use Firecrawl to scrape the web and gather information."
description = "An agent that can use Firecrawl to scrape the web and gather information."
readme = """
# Firecrawl Agent

This is a simple agent that uses the Firecrawl API to scrape the web and gather information. It can be used to gather information for other agents, or to perform tasks that require web scraping.

This agent supports bringing your own key if ran locally.
"""

[agent.license]
type = "text"
text = "apache-2.0"

[marketplace]

[options]
MAX_ITERATIONS = { type = "u32", default = 40, display.description = "The maximum number of LLM iterations (ignoring tool calls) to run." }
ITERATION_DELAY = { type = "u64", display.description = "The number of seconds to wait between iterations.  If left unspecified, no delay will occur between iterations." }
MAX_TOKENS = { type = "u32", default = 45000, display.description = "The maximum number of tokens to use for this agent during the entire session." }

[options.INITIAL_USER_PROMPT]
type = "string"
display.description = "The prompt to use for the initial user message."
default = """
[automated message] You are an autonomous agent designed to assist users by collaborating with other agents.
If no instructions are provided, consider waiting for mentions until another agent provides further direction.
Remember that 'I' am not the user, who is not directly reachable. Use tools to interact with other agents as necessary to fulfil the users needs. You will receive further automated messages this way.
"""
display.multiline = true

[options.FOLLOWUP_USER_PROMPT]
type = "string"
display.description = "The prompt to use for follow-up iterations."
default = """
[automated message] Continue fulfilling your responsibilities collaboratively to the best of your ability.
"""
display.multiline = true

[options.FIRECRAWL_API_KEY]
type = "string"
display.description = "The API key to use for Firecrawl. You can obtain an API key by signing up for a free account at https://firecrawl.com"
secret = true

[options.SYSTEM_PROMPT]
type = "string"
display.description = "The system prompt to use"
default = """
You are the Firecrawl agent. You must use your unique Firecrawl tooling at request by other agents.
"""
display.multiline = true

[options.EXTRA_SYSTEM_PROMPT]
type = "string"
display.description = "Additional system prompt instructions to customize the agent's behavior."
display.multiline = true

[runtimes.executable]
path = "../target/release/agent-firecrawl"

[runtimes.docker]
image = "coralprotocol/agent-firecrawl"
