edition = 2

[agent]
name = "firecrawl"
version = "0.0.1"

[options]
MAX_ITERATIONS = { type = "u32", default = 20, display.description = "The maximum number of LLM iterations (ignoring tool calls) to run." }
ITERATION_DELAY = { type = "u64", display.description = "The number of seconds to wait between iterations.  If left unspecified, no delay will occur between iterations." }
MAX_TOKENS = { type = "u32", default = 20000, display.description = "The maximum number of tokens to use for this agent during the entire session." }

[options.EXTRA_SYSTEM_PROMPT]
type = "string"
display.description = "Additional system prompt instructions to customize the agent's behavior."
display.multiline = true

[options.FOLLOWUP_USER_PROMPT]
type = "string"
display.description = "The prompt to use for follow-up iterations."
default = """
1. Use Coral tooling to wait for messages that you can provide assistance to
2. Use Firecrawl tooling as requested by other agents
3. Respond to the agent that needed assistance using Coral tooling
"""
display.multiline = true

# Uncomment this option to pass in the API key as an option instead of relying on additional_docker_environment.MODEL_PROVIDER_URL
#[options.MODEL_PROVIDER_URL]
#type = "string"
#description = "The base URL for the LLM provider API (OpenAI compatible)"
#default = "https://openrouter.ai/api/v1/chat/completions"

# Uncomment this option to pass in the API key as an option instead of relying on additional_docker_environment.MODEL_API_KEY
#MODEL_API_KEY = { type = "string", required = true, description = "The API key for the LLM provider (OpenAI compatible)" }

#MODEL_ID = { type = "string", default = "openai/gpt-5-mini", description = "The model ID to use for the LLM provider" }

#DEVIN_API_KEY = { type = "string", display.description = "The devin.ai api key/token" }


[options.SYSTEM_PROMPT]
type = "string"
display.description = "The system prompt to use"
default = """
You are the Firecrawl agent.  You must use your unique Firecrawl tooling at request by other agents.
"""
display.multiline = true

[runtimes.executable]
command = ["W:\\Coral\\agents\\rust\\target\\release\\agent-firecrawl.exe"]

[runtimes.docker]
image = "coralprotocol/agent-firecrawl"